=== nicoduflot/2024-01-22-XML/05-intro-xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="rolodex">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="personne">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="nom" type="xsd:string" />
                            <xsd:element name="prenom" type="xsd:string" />
                            <xsd:element name="adresses">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="adresse">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="numero" type="xsd:string" />
                                                    <xsd:element name="voie" type="xsd:string" />
                                                    <xsd:element name="codePostal" type="xsd:string" />
                                                    <xsd:element name="ville" type="xsd:string" />
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <!-- xsd de la balise emails -->
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== nicoduflot/2024-01-22-XML/05-intro-xsd.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rolodex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="05-intro-xsd.xsd">
    <personne>
        <nom>Duflot</nom>
        <prenom>Nicolas</prenom>
        <adresses>
            <adresse>
                <numero>3</numero>
                <voie>Rue du parc</voie>
                <codePostal>75001</codePostal>
                <ville>Paris</ville>
            </adresse>
        </adresses>
    </personne>
</rolodex>
